---
# tasks file for wiki js
- name: Install Node.js package
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Create Wiki.js user
  ansible.builtin.group:
    name: "{{ wiki_js_group }}"
    state: present

- name: Create Wiki.js user
  ansible.builtin.user:
    name: "{{ wiki_js_user }}"
    group: "{{ wiki_js_group }}"
    shell: /sbin/nologin
    create_home: false
    state: present

- name: Create Wiki.js directory
  ansible.builtin.file:
    path: /opt/wiki-js
    state: directory
    owner: "{{ wiki_js_user }}"
    group: "{{ wiki_js_group }}"
    mode: "0755"

- name: Get the latest version of wiki.js
  ansible.builtin.unarchive:
    src: https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
    dest: /opt/wiki-js
    owner: "{{ wiki_js_user }}"
    group: "{{ wiki_js_group }}"
    remote_src: true
  notify: Restart Wiki.js

- name: Create configuration file
  ansible.builtin.template:
    src: config.yml.j2
    dest: /opt/wiki-js/config.yml
    mode: "0664"
    owner: "{{ wiki_js_user }}"
    group: "{{ wiki_js_group }}"
  notify: Restart Wiki.js

- name: Ensure Wiki.js service file is on remote
  ansible.builtin.template:
    src: wiki.service.j2
    dest: /etc/systemd/system/wiki.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart Wiki.js

- name: Ensure Wiki.js service is started and enabled
  ansible.builtin.systemd:
    name: wiki
    state: started
    enabled: true
