---
# tasks file for wiki js
- name: Install packages
  ansible.builtin.package:
    name:
      - nodejs
    state: present

- name: Get the latest version of wiki.js
  ansible.builtin.unarchive:
    src: https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
    dest: /opt
    owner: "{{ wiki_js_user }}"
    group: "{{ wiki_js_group }}"
    remote_src: true
  notify: Restart Wiki.js

- name: Create configuration file
  ansible.builtin.template:
    src: config.yml.j2
    dest: /opt/wiki/config.yml
    mode: "0664"
    owner: "{{ wiki_js_user }}"
    group: "{{ wiki_js_group }}"
  notify: Restart Wiki.js

- name: Ensure Wiki.js service file is on remote
  ansible.builtin.template:
    src: wiki.service.j2
    dest: /etc/systemd/system/wiki.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart Wiki.js

- name: Ensure Wiki.js service is started and enabled
  ansible.builtin.service:
    name: wiki
    state: started
    enabled: true
